apiVersion: v1
kind: Service
metadata:
  name: datacamp-service
spec:
  selector:
    app: datacamp-app
  ports:
    - protocol: TCP             # this is merely the default protocol
      port: 9876                # this is the port for reaching the service
      targetPort: our-svc-port  # this is the named port declared in the deployment